name: untitled23
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1

  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
